---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[django::default]
    attributes:
  - name: install_pip
    run_list:
      - recipe[django::install_pip]
    attributes:
  - name: install_virtualenv
    run_list:
      - recipe[django::install_virtualenv]
    attributes:
